### ISSUE TITLE
Question about outline of report

### ISSUE THREAD

**Issue by wouterRUG** [RUG-IDS/Assignments#11]
Hello everyone,

I have a question about the outline of the report. In the exercise they state that you have to write something about 'relevant work' (include at least three resources). 
What is expected there? Do we simply write a section in our report where we introduce the used references? 
What is the difference between 'relevent work' and the 'main study'? The whole notion of 'relevant work' is a little bit vague to me and I would greatly appreciate it if you could elaborate on it.

Thanks in advance,
Wouter (team 03)

**Comment by HanKruiger** [comment]
Hi Wouter,

(In my view) For papers, the aim of a *relevant work* section is usually to provide context for your work. This can be e.g. an overview of the field of study, or a short survey of recent relevant studies. Important is to not only cite the references, also provide a short take-away of the cited work and if possible, how it relates to your work.

Best,
Han
