### ISSUE TITLE
No grades assignment 1 online

### ISSUE THREAD

**Issue by wouterRUG** [RUG-IDS/Assignments#14]
Hello,

My teammates told me that the grades for assignment 1 are on Nestor, however they are not visible to me. Did something go wrong?

Kind regards,
Wouter Baar

**Comment by HanKruiger** [comment]
Hi Wouter,

Thanks for letting us know! Indeed, something went wrong on our part. We will add your grade to Nestor.

Best,
Han

**Comment by HanKruiger** [comment]
Your grade should be updated now.

**Comment by wouterRUG** [comment]
Thank you!
Yes indeed, they are visible now :)
