### ISSUE TITLE
Bonus Assignment & Points

### ISSUE THREAD

**Issue by michel-medema** [RUG-IDS/Assignments#19]
The bonus assignment asks to implement an association rule mining algorithm by hand. However, at least for the case of Matlab, the Apriori algorithm is already implemented in the file `findRules.m` that has been provided. Will re-implementing the Apriori algorithm in Matlab still give (potentially) full points for the bonus assignment, or should some other algorithm be implemented?

Moreover, unlike the previous assignments, the total number of points for the non-bonus part of the assignment does not seem to sum to 100 points. Is this correct and does 90 points equal a 10, or should the number of points for part of the assignment be different?

**Comment by HanKruiger** [comment]
Excellent questions.

For the implementation of an AR mining algorithm, you have to implement it yourself. In you own words, so to say. Of course there are implementations available on the web (or in Nestor, apparently) that you can use as inspiration. But you have to be able to explain why everything (of your own implementation) is there.

For the sum of the number of points. Good observation. We'll discuss this with the staff this afternoon. Thanks for **point**ing this out.
