### ISSUE TITLE
Bonus points when submitted as group assignment

### ISSUE THREAD

**Issue by Hoeksema** [RUG-IDS/Assignments#2]
In the last announcement:

>However, if the entire team (or a subset of it) decides to work together and submit the extra assignment, then you can do that and mention this in the notes at the end of the report.

Can I assume you can still get full bonus points (as a group) if you don't submit them individually, or will there be some kind of penalty to the bonus for submitting as a group?

**Comment by mircealungu** [comment]
There will be no penalty for collaboration :)
