### ISSUE TITLE
Coordinates between 6d and 3d assignment 5, and particle mass

### ISSUE THREAD

**Issue by adriaan-vd-graaf** [RUG-IDS/Assignments#22]
The coordinates are different between the 6d and 3d file. How was normalization perfomed, and what are the dimensions of the velocity and position?

And is the mass the same of every data point?

**Comment by HanKruiger** [comment]
The assignment document has the answer.

> Based on astronomical knowledge transformed features of the stars has been extracted corresponding to energy, angular momentum, and angular momentum along the z-axis. These 3-dimensional vectors explaining the same stars can be found in stars 3d.txt

The 3d dataset are not coordinates in regular space. They're in a 3d feature space.
