### ISSUE TITLE
Units of the data

### ISSUE THREAD

**Issue by Fonotec** [RUG-IDS/Assignments#23]
What are the units of the coordinates (kpc?), velocities (km/s?), energies (ergs?), angular momentum (solar mass km /s ?). And further are the masses of all stars the same (1 solar mass?)

**Comment by kbunte** [comment]
Hello, I contacted the owner of that data set about your questions and come back with the answer.

**Comment by kbunte** [comment]
Just got a response:

The units of velocity are km/s. The distance units are kilo parsecs. Energy is computed per unit mass, and so has the units of (km/s)^2
The simulations are run assuming that all stars have the same mass. As a result, mass drops out of the equations. This is not an unreasonable assumption, given that most of the stars are rather old (much more than the Sun), and so the variation in mass is negligible for our purposes.

**Comment by Fonotec** [comment]
Okay thanks for the effort, this helps!
