### ISSUE TITLE
Hopkins statistic test unclear explanation

### ISSUE THREAD

**Issue by joelgrondman** [RUG-IDS/Assignments#24]
I've tried to apply the Hopkins statistic in the slides to part 1 of assignment 4 but the slides describing the Hopkins statistic leave out too much detail or is incorrect so I'm not sure if the results I'm getting are correct.

e.g. in the slides 04-clustering.pdf on page 25 step 2 it says to compute the minimum distance of all data points to the sampled data points which would be 0 and probably not correct. Same with step 4.

Is there a source where the Hopkins statistic can be found?

**Comment by HanKruiger** [comment]
You're encouraged to explore questions like this yourself, but [allow me to do it for you](https://lmgtfy.com/?q=hopkins+statistic). (Excuse my sense of humour.)

**Comment by joelgrondman** [comment]
If you can't answer the question then there is no need for you to answer ;)

**Comment by HanKruiger** [comment]
The [first search result](http://www.sthda.com/english/wiki/assessing-clustering-tendency-a-vital-issue-unsupervised-machine-learning#hopkins-statistic) has a quite clear explanation. :-)

**Comment by joelgrondman** [comment]
That link has the same explanation as the slides.
I found some [code](https://fricke.co.uk/DandA/hopkins.htm) that did prove helpful.
For anyone else stuck with the algorithm step 2 from the algorithm should be: compute the distance between each sample point `p_{i}` and closest neighbor in `D` to get `x_{i}` for all `i` in `[1,...,n]`
