### ISSUE TITLE
How is the final grade for the assignments calculated.

### ISSUE THREAD

**Issue by adriaan-vd-graaf** [RUG-IDS/Assignments#27]
Hello,

While the end of the course is nearing, I was wondering  how the final assignment grade is determined. 
Is it the (total points / 600) or something else?

Thanks, Adriaan

**Comment by adriaan-vd-graaf** [comment]
Also, where are the grades for assignment 4? 
It's been a while since we submitted it.

**Comment by mircealungu** [comment]
The final assignment grade is indeed Total Points / 600. 
I still want to check personally a few of the assignment 4's before we publish the grades. 
By tomorrow you'll have them.

**Comment by Hoeksema** [comment]
Hi Mircea,

Considering there were 90 non-bonus points for assignment 4 instead of 100, I think that should be / 590, shouldn't it?

Regards,
Thomas

**Comment by poshposh** [comment]
Hi,
If we have above 50% in 4 mandatory assignments and one optional assignment, would that be enough? Or should all 5 be mandatory exercises?

**Comment by mircealungu** [comment]
You must have 5 assignments above 50%, you choose which, including the optional 7. 
In total, the points you have divided by 590 should be above 295 points. 
(And these points also include the bonus points.)
