### ISSUE TITLE
Code in pdf?

### ISSUE THREAD

**Issue by NHartsuiker** [RUG-IDS/Assignments#3]
Hello,
We were wondering if you would appreciate the code being added as an appendix in the pdf (lslisting), or if the code simply being included in the pull request suffices.

Kind regards on behalf of team 11,
Nadia Hartsuiker

**Comment by HanKruiger** [comment]
The code is only required to be included in the pdf report if the question is really about implementing a specific thing and requires elaboration. In the first assignment there are no questions like this.

If you use an interactive report (e.g. RMarkdown/Jupyter) you have to include the code of course.

Of course the code in the pull request should be runnable and well documented (with comments).
