### ISSUE TITLE
Missing assignment 5 grade

### ISSUE THREAD

**Issue by wouterRUG** [RUG-IDS/Assignments#30]
Hello, 
My grade for assignment 5 is missing (it's still 'upcoming'). The grade is visible for my teammates so I think something went wrong. Could you have a look at this? 
I am in team 03, s-number 2394790. 
Thanks in advance and kind regards,
Wouter Baar

**Comment by richardwmak** [comment]
I'm going to hijack this issue: I have the same problem except for assignment 6. For me too my teammates have a grade already.
I am team 08, s-number 2313278.

Richard Mak

**Comment by mircealungu** [comment]
Hi Wouter & Richard,

I've updated your grades in Nestor. 

Cheers.
M.
