### ISSUE TITLE
Flipchart - Group 02

### ISSUE THREAD

**Issue by HC94** [RUG-IDS/Assignments#5]
Hi,

Could you provide Group 02 a flipchart (preferably including paper and markers) for the presentation on Wednesday, 30th of November? 

Thanks,
Group 2

**Comment by JorritdeV** [comment]
Hi group 2, 

That should be no problem. Ill inform you once I have confirmation.

Regards,

Jorrit

**Comment by JorritdeV** [comment]
Hi Group 2, 

I was wondering if a whiteboard would be sufficient as well. I pretty sure I can get you a flipchart, a whiteboard I have for certain though. 

Jorrit

**Comment by HC94** [comment]
Whiteboard would be fine as well. Thank you!
